import Foundation

/// Entirely synthetic content and identifiers, never a real account or route.
public enum PlayExperienceSyntheticFixtures {
    public static let classic = #"{"topicId":71,"topicName":"Synthetic journey","mode":1,"registered":true,"playable":true,"total":1,"doneCount":0,"nodes":[{"nodeId":701,"name":"Synthetic courtyard","done":false,"arrived":true,"validationMethod":1,"question":"Enter your own synthetic answer","hintLocked":true,"hintCost":2,"puzzleHintLevel":0,"puzzleScoreCap":100}]}"#
    public static let complete = #"{"topicId":71,"topicName":"Synthetic journey","mode":1,"registered":true,"playable":true,"total":1,"doneCount":1,"nodes":[{"nodeId":701,"name":"Synthetic courtyard","done":true,"arrived":true,"validationMethod":1,"xp":9}]}"#
    public static let branch = #"{"topicId":71,"topicName":"Synthetic branch","mode":1,"registered":true,"playable":true,"total":2,"doneCount":0,"nodes":[{"nodeId":701,"name":"Synthetic courtyard","done":false,"arrived":true,"validationMethod":1,"question":"Synthetic answer"},{"nodeId":702,"name":"Hidden synthetic node","done":false}],"routeState":{"routeMode":"BRANCH_GRAPH","sessionId":501,"status":"ACTIVE","version":2,"nodeStates":{"701":"PLAYABLE","702":"HIDDEN"}}}"#
    public static let route = #"{"routeMode":"BRANCH_GRAPH","sessionId":501,"status":"ACTIVE","version":2,"nodeStates":{"701":"PLAYABLE","702":"HIDDEN"}}"#
    public static let mode2 = #"{"topicId":71,"topicName":"Synthetic store day","mode":2,"registered":true,"playable":true,"total":1,"doneCount":0,"nodes":[{"nodeId":701,"merchantId":81,"name":"Synthetic shop","done":false,"arrived":true,"selfReported":true,"photoRequireDesc":"Synthetic sign only"}]}"#
    public static let player = #"{"perspective":"PLAYER","activityId":41,"sessionId":501,"revision":2,"status":"RUNNING","availableActions":["CONFIRM_ROLE","PLAYER_CHOICE","PLAYER_SUBMIT","PLAYER_HINT","PLAYER_REVEAL"],"player":{"teamId":61,"role":{"code":"OBSERVER","name":"Synthetic observer","confirmed":true,"publicBrief":"Synthetic role brief"},"nodes":[{"nodeId":701,"nodeName":"Synthetic courtyard","personalState":"ACTIVE","stationStatus":"ACTIVE","clue":"Synthetic clue","allowedChoices":[{"id":"LEFT","label":"Synthetic left path"}],"playerTask":{"taskCode":"OBSERVE","prompt":"Write a synthetic observation","inputType":"TEXT"},"hint":{"nextLevel":1,"currentLevel":0,"nextImpactLabel":"Synthetic score cap may change","revealAvailable":true,"revealImpactLabel":"Synthetic assisted completion gives zero puzzle score"}}],"mySubmissions":[],"story":{}}}"#
    public static let advanced = #"{"sessionId":601,"activityId":41,"topicId":71,"nodeId":701,"version":2,"status":"RUNNING","readyForBase":false,"score":5,"present":"inline","config":{"random":{"enabled":true},"branch":{"enabled":true}},"branch":{"currentStepId":"first","currentStep":{"id":"first","title":"Synthetic branch","body":"Pick a source-provided option","options":[{"id":"left","label":"Synthetic left"}]}},"draws":[],"playKit":{"coinFlip":{"title":"Synthetic coin"}}}"#
    public static let board = #"{"list":[{"rank":1,"memberId":9001,"nickname":"Synthetic player","score":1}],"me":{"rank":1,"memberId":9001,"nickname":"Synthetic player","score":1}}"#
    public static let lead = #"{"exists":true,"status":1,"leaderMemberId":9001,"isLeader":true,"currentChapterId":81,"chapterName":"Synthetic chapter","arrived":1,"meArrived":true,"members":[{"memberId":9001,"nickname":"Synthetic leader","done":0,"arrived":true,"isLeader":true}]}"#
    public static func wire(_ json: String) throws -> PlayWireValue { try JSONDecoder().decode(PlayWireValue.self, from: Data(json.utf8)) }
    public static func envelope(_ raw: String) -> Data { Data(("{\"code\":200,\"data\":" + raw + "}").utf8) }
}
