#if DEBUG
import Foundation

/// Generated bytes and a local response through the actual bounded client. No document or network.
@MainActor final class ProjectStoryAudioSynthetic: ProjectStoryAudioUploading {
    @MainActor final class Wire: HTTPTransport {
        var requests: [URLRequest] = []
        var beforeReply: (() -> Void)?
        var unknownOnce = false, held = false
        var pending: CheckedContinuation<Void, Never>?
        func release() { let old = pending; pending = nil; old?.resume() }
        var reference = "https://example.com/synthetic/story/e%CC%81.m4a?version=1"
        func send(_ request: URLRequest) async throws -> (Data, Int) {
            requests.append(request)
            guard request.url?.path == "/" + ProjectStoryAudioUploadClient.path else { throw APIError.invalidRequest }
            reference = "https://example.com/synthetic/story/e%CC%81.m4a?version=\(requests.count)"
            if held { await withCheckedContinuation { pending = $0 } }
            beforeReply?()
            if unknownOnce { unknownOnce = false; throw URLError(.networkConnectionLost) }
            return (try JSONEncoder().encode(["code": ProjectEditJSON.number(200), "url": .string(reference)]), 200)
        }
    }
    @MainActor final class Picker: ProjectStoryAudioSelecting {
        let audio: ProjectStorySelectedAudio
        var cancelNext = false
        private var cancelled = false
        init(_ audio: ProjectStorySelectedAudio, cancelNext: Bool = false) { self.audio = audio; self.cancelNext = cancelNext }
        func select() async throws -> ProjectStorySelectedAudio? {
            if cancelled { return nil }
            if cancelNext { cancelNext = false; return nil }
            return audio
        }
        func cancel() { cancelled = true }
    }
    let picked: ProjectStorySelectedAudio
    let wire: Wire
    private let client: ProjectStoryAudioUploadClient
    var uploadCount: Int { wire.requests.count }
    var reference: String { wire.reference }
    init(session: ProjectEditSession, unknownOnce: Bool = false, beforeReply: (() -> Void)? = nil,
         currentSession: @escaping () -> ProjectEditSession?) throws {
        let bytes = Data("Test-only synthetic audio bytes; no decoder claim".utf8)
        var offset = 0
        picked = try ProjectStoryAudioCapture.read(filename: "Synthetic e\u{301}.m4a", reportedByteCount: bytes.count, checkCancellation: {},
            readChunk: { count in let end = min(offset + count, bytes.count); defer { offset = end }; return bytes.subdata(in: offset..<end) })
        let wire = Wire(); self.wire = wire; wire.unknownOnce = unknownOnce; wire.beforeReply = beforeReply
        let configuration = try APIConfiguration(baseURL: URL(string: "https://example.com")!)
        let approval = try ProjectStoryAudioUploadApproval(baseURL: configuration.baseURL, namespace: session.storageNamespace,
            accountID: session.accountID, approvedOrigins: ["https://example.com"], nativePicker: true)
        client = .init(configuration: configuration, approval: approval, transport: wire, credentials: {
            guard let current = currentSession(), current == session else { return nil }
            return try? .init(session: current, token: "synthetic-story-audio")
        }, currentApproval: { currentSession() == session ? approval : nil })
    }
    func isCurrent(session: ProjectEditSession) -> Bool { client.isCurrent(session: session) }
    func permitsPicker(session: ProjectEditSession) -> Bool { client.permitsPicker(session: session) }
    func permitsReference(_ reference: String, session: ProjectEditSession) -> Bool { client.permitsReference(reference, session: session) }
    func upload(_ audio: ProjectStorySelectedAudio, attemptID: UUID, session: ProjectEditSession) async throws -> ProjectStoryUploadedAudio {
        try await client.upload(audio, attemptID: attemptID, session: session)
    }
}
#endif
