from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
rows={
 'title':('Community governance','社区治理'),'signIn':('Sign in to view account governance','登录后查看账号社区治理'),'refresh':('Refresh','刷新'),'drafts':('My drafts and pending content','我的草稿与待复审内容'),
 'preferences':('Notification preferences','通知偏好'),'interactionEnabled':('Interactions and replies','互动与回复'),'mentionEnabled':('Mentions','提及我'),'socialEnabled':('Social updates','社交动态'),'governanceAlways':('Safety, enforcement and appeal results always arrive','安全、处置与申诉结果始终送达'),
 'unknownLocked':('Unavailable: permission or state is unknown','不可操作：权限或状态尚不明确'),'notifications':('Community notifications','社区通知'),'emptyNotifications':('No notifications','暂无社区通知'),'unread':('Unread','未读'),'read':('Read','已读'),'markRead':('Mark as read','标为已读'),'openPost':('Open post','查看帖文'),'moreNotifications':('Load more notifications','加载更多通知'),
 'enforcements':('Enforcements and appeals','处置与申诉'),'emptyEnforcements':('No enforcement records','没有社区处置记录'),'appeal':('Request review','申请复核'),'moreEnforcements':('Load more records','加载更多处置记录'),'appealFacts':('Explain the facts you would like reviewed. No evidence upload is supported by this source flow.','说明需要复核的事实。此来源流程不支持上传申诉证据。'),'reason':('Facts for review','需要复核的事实'),
 'comments':('Comment controls','评论管理'),'commentRoles':('Post authors can approve pending comments. Only comment authors can delete their own comments. Moderator status alone does not grant these actions.','帖文作者可批准待审评论；只有评论作者可删除自己的评论。管理员身份本身不授予这些操作权限。'),'approveComment':('Approve pending comment','批准待审评论'),'deleteComment':('Delete my comment','删除我的评论'),
 'review':('Review request','核对请求'),'reviewWarning':('Review the account, target and exact change. Confirmation checks fresh server facts again. Acknowledgement does not establish the final moderation outcome.','请核对账号、对象和具体更改。确认前将重新检查服务端事实。请求受理不代表最终处置结果。'),'liveDisabled':('This operation is disabled. A separately reviewed transport grant is required.','此操作已关闭，需另行核准对应传输权限。'),'confirm':('Confirm reviewed request','确认已核对的请求'),'cancel':('Cancel','取消'),'account':('Account','账号'),'version':('Expected version','预期版本'),'enabled':('Enabled','开启'),'disabled':('Disabled','关闭'),'deleteWarning':('This targets only your comment. Review before requesting deletion.','此操作仅针对你的评论。请求删除前请核对。'),
 'acknowledged':('Request acknowledged. Refresh to verify status; this is not proof of an approved appeal or deleted comment.','请求已受理。请刷新核实状态；这不代表申诉成功或评论已删除。'),'stale':('Facts changed or review expired. Refresh and review again.','事实已变化或核对已过期。请刷新后重新核对。'),'unknownOutcome':('This request is locked against repetition. Its outcome must be independently verified.','此请求已锁定，不能重复提交。需独立核实结果。'),'forbidden':('This account does not have the required permission.','此账号没有所需权限。'),'error':('Unable to complete. Refresh to retry reading; nothing is assumed successful.','未能完成。可刷新重试读取；不假定操作成功。'),'synthetic':('Synthetic fixture • no network or real moderation','合成测试 · 不联网、不执行真实处置')}
notices={ 'LIKE':('Someone liked your post','有人喜欢了你的帖文'),'BOOKMARK':('Someone bookmarked your post','有人收藏了你的帖文'),'COMMENT':('Someone replied to your post','有人回复了你的帖文'),'REPLY':('Someone replied to your comment','有人回复了你的评论'),'COMMENT_LIKE':('Someone liked your comment','有人喜欢了你的评论'),'POST_MENTION':('You were mentioned in a post','有人在帖文中提及你'),'APPROVED':('Your post was approved','你的帖文已通过审核'),'REMOVED':('Your post did not pass review','你的帖文未通过审核'),'APPEAL_SUBMITTED':('Appeal submitted','申诉已提交'),'APPEAL_UPHELD':('Appeal review completed','申诉复核已完成'),'APPEAL_REVERSED':('Enforcement reversed after appeal','申诉成功，处置已撤销'),'FEATURED':('Your post was featured','你的帖文已被收录到精选'),'FOLLOW':('Someone followed you','有人关注了你'),'GUIDELINE_UPDATED':('Community guidelines updated','社区规范已更新'),'REPORT_RECEIVED':('Your report was received','你的举报已受理'),'REPORT_STAGE':('Your report progress changed','你的举报进度已更新'),'UNKNOWN':('Community update','社区动态')}
rows.update({'notice.'+k:v for k,v in notices.items()})
catalog={'sourceLanguage':'en','version':'1.0','strings':{'square.gov.'+k:{'localizations':{lang:{'stringUnit':{'state':'translated','value':value}} for lang,value in zip(['en','zh-Hans'],values)}} for k,values in rows.items()}}
(root/'Resources/SquareGovernanceLocalizations.fragment.json').write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
print(len(rows))
