#!/usr/bin/env python3
"""Merge this slice's bilingual strings without replacing unrelated catalog entries."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
PAIRS = {
'social.fixtureSwitchAccount': ('Switch example account', '切换示例账号'),
'social.notConfigured': ('This service is not configured.', '此服务尚未配置。'),
'social.signIn': ('Sign in to continue.', '请登录后继续。'),
'social.emptyText': ('Enter some text before reviewing.', '请先输入内容再预览。'),
'social.ownerRequired': ('Only the post owner can edit this post.', '只有作者可以编辑这篇动态。'),
'social.commentsClosed': ('Comments are unavailable for this post.', '此动态暂不可评论。'),
'social.changed': ('The account or content changed. Open a new review.', '账号或内容已变化，请重新预览。'),
'social.failed': ('Unable to load this information. Try again.', '暂时无法获取信息，请重试。'),
'social.offline': ('Offline example. All people, records and outcomes here are synthetic.', '离线示例。人物、记录和结果均为虚构测试数据。'),
'social.loading': ('Loading…', '正在加载…'),
'social.incompleteLink': ('This link is incomplete. Go back to choose another item.', '链接不完整，请返回选择其他内容。'),
'social.profile': ('Public profile', '公开主页'),
'social.profileSection': ('Profile section', '主页内容'),
'social.level': ('Level', '等级'),
'social.followStatus': ('Relationship', '关注关系'),
'social.following': ('Following', '已关注'),
'social.notFollowing': ('Not following', '未关注'),
'social.relationshipUnknown': ('Sign in to see your relationship', '登录后查看关注关系'),
'social.profileActionsDisabled': ('Follow and conversation actions can be reviewed. Live actions remain unavailable.', '可预览关注和发起会话操作，线上操作暂未开放。'),
'social.posts': ('Posts', '动态'),
'social.achievements': ('Achievements', '成就'),
'social.about': ('About', '关于'),
'social.published': ('Published routes and activities', '已发布路线和活动'),
'social.likes': ('Likes received', '获赞'),
'social.followers': ('Followers', '粉丝'),
'social.followingCount': ('Following', '关注人数'),
'social.introduction': ('Introduction', '个人介绍'),
'social.noIntroduction': ('No introduction provided.', '暂无个人介绍。'),
'social.interests': ('Interests', '兴趣'),
'social.noInterests': ('No interests provided.', '暂无兴趣标签。'),
'social.portfolio': ('Exploration portfolio', '探索作品'),
'social.postsSignIn': ('Sign in to load this member’s posts.', '登录后查看该用户的动态。'),
'social.noPosts': ('No posts yet.', '暂无动态。'),
'social.guide.title': ('Play guide', '玩法指南'),
'social.guide.modes': ('Ways to explore', '探索方式'),
'social.guide.classic': ('City orienteering', '城市定向'),
'social.guide.free': ('Free exploration', '自由探索'),
'social.guide.roam': ('Roaming', '漫游'),
'social.guide.classicDetail': ('Follow checkpoints in order with your group. Good for planned meetups and story-based routes.', '和队友按顺序打卡通关，适合约人同行和有剧情的路线。'),
'social.guide.freeDetail': ('Explore open checkpoints in your own order and at your own pace.', '点位全部开放，按自己的顺序和节奏探索。'),
'social.guide.roamDetail': ('Walk and discover the city with no required finish line.', '边走边探索城市，不必追赶终点。'),
'social.guide.explore': ('Explore', '去探索'),
'social.guide.information': ('More information', '更多说明'),
'social.guide.empty': ('Published guides will appear here.', '玩法说明上线后会显示在这里。'),
'social.guide.removed': ('This guide is no longer available. Go back to the guide list.', '这篇说明已不可用，请返回玩法列表。'),
'social.guide.noContent': ('This guide does not have readable content yet.', '这篇说明暂时没有正文。'),
'social.invites.title': ('Invitation history', '邀请记录'),
'social.invites.total': ('Total invited', '累计邀请'),
'social.invites.loaded': ('Loaded records', '已加载记录'),
'social.invites.partial': ('Invitation records are available, but rewards are not fully synchronized. Missing rewards do not establish that a first purchase is pending.', '邀请记录已获取，奖励流水尚未完整同步。未查到奖励不代表首购尚未完成。'),
'social.invites.otherMonth': ('Other invitations', '其他邀请'),
'social.invites.empty': ('Your invited members will appear here after they join.', '受邀用户加入后会显示在这里。'),
'social.invites.continuationInvalid': ('The next page repeated existing records. Refresh to try again.', '下一页重复了已有记录，请刷新后重试。'),
'social.invites.timeUnknown': ('Invitation time not recorded', '邀请时间暂未记录'),
'social.invites.earned': ('First-purchase reward received', '首购奖励已到账'),
'social.invites.pending': ('Joined · first purchase pending', '已加入 · 首购待完成'),
'social.invites.synchronizing': ('Joined · reward not synchronized', '已加入 · 奖励待同步'),
'social.invites.points': ('Reward points', '奖励积分'),
'social.writesDisabled': ('Review only. Live posting, replies, reactions, reports, follows and conversation creation are disabled.', '仅供预览。线上发帖、回复、互动、举报、关注和创建会话均未开放。'),
'social.targetPost': ('Post ID', '动态编号'),
'social.targetComment': ('Comment ID', '评论编号'),
'social.targetMember': ('Member ID', '用户编号'),
'social.currentAccount': ('Current account ID', '当前账号编号'),
'social.text': ('Text', '正文'),
'social.editPreservesMedia': ('Editing text keeps the existing images and linked activity or route.', '编辑文字会保留已有图片和关联活动或路线。'),
'social.actionEnabled': ('Enable this action', '开启此操作'),
'social.explicitActionHint': ('This is the requested state, not a claim about the current saved state.', '此处是希望设置的状态，不代表服务端当前状态。'),
'social.toggleHint': ('The source action toggles the existing comment like. An uncertain result must not be retried automatically.', '此操作会切换评论点赞状态。结果未确认时不能自动重试。'),
'social.reportHint': ('Send this item to the review queue. The source endpoint accepts the item ID only, with no reason or evidence fields.', '将此内容提交审核队列。源接口只接受内容编号，不接受理由或证据字段。'),
'social.followToggleHint': ('Toggle the current follow relationship once. The server must confirm the resulting relationship; an uncertain result stays locked.', '切换一次当前关注关系。结果必须由服务端确认，未确认时保留锁定。'),
'social.startChatHint': ('Request a conversation with this member. Navigation requires a positive conversation ID from the server.', '请求与该用户建立会话，只有服务端返回有效会话编号后才能打开聊天。'),
'social.review': ('Review', '预览'),
'social.reviewTarget': ('Review target', '确认操作对象'),
'social.willEnable': ('Requested state: enabled', '期望状态：开启'),
'social.willDisable': ('Requested state: disabled', '期望状态：关闭'),
'social.moderationHint': ('An acknowledgement does not prove that content is published or visible. The server remains authoritative.', '请求已确认不等于内容已发布或可见，最终结果以服务端为准。'),
'social.simulate': ('Simulate this example', '模拟示例操作'),
'social.submit': ('Submit', '提交'),
'social.notSent': ('Nothing was sent. Start a new review when ready.', '未发送任何内容，可重新预览。'),
'social.rejected': ('The request was rejected. Review the content before trying again.', '请求被拒绝，请检查内容后再操作。'),
'social.unknown': ('The outcome is unknown. This action is locked to avoid duplicates. Returning or signing in again will not retry it.', '操作结果未确认，已锁定以防重复。返回页面或重新登录不会重试。'),
'social.simulated': ('Synthetic acknowledgement only. Nothing was sent externally.', '仅为模拟确认，未向外部发送任何内容。'),
'social.acknowledged': ('The server acknowledged the request. Refresh the original page for the current state.', '服务端已确认请求，请刷新原页面查看最新状态。'),
'social.actions': ('Actions', '操作'),
'social.viewAuthor': ('View author profile', '查看作者主页'),
'social.reply': ('Reply', '回复'),
'social.editor.createPost': ('Write a post', '写动态'),
'social.editor.editPost': ('Edit post text', '编辑动态文字'),
'social.editor.comment': ('Write a comment', '写评论'),
'social.editor.like': ('Post like', '动态点赞'),
'social.editor.bookmark': ('Bookmark', '收藏动态'),
'social.editor.commentLike': ('Toggle comment like', '切换评论点赞'),
'social.editor.report': ('Report content', '举报内容'),
'social.editor.toggleFollow': ('Follow relationship', '关注关系'),
'social.editor.startChat': ('Start a conversation', '发起会话'),
'social.media.title': ('Image preview', '图片预览'),
'social.media.image': ('Message image', '消息图片'),
'social.media.disabled': ('Live image loading awaits approved media origins and size-limited downloads.', '线上图片加载需先确认媒体来源并验证下载大小限制。'),
'social.media.purpose': ('Loading connects to the media host below without account credentials. No upload is performed.', '加载时会连接下方媒体站点，不发送账号凭据，也不会上传内容。'),
'social.media.load': ('Load image', '加载图片'),
'social.media.failed': ('The image could not be loaded or decoded safely.', '图片无法加载或安全解码。'),
'social.media.invalid': ('This message does not contain a supported secure image address.', '这条消息不包含支持的安全图片地址。'),
}
if __name__ == '__main__':
    path = ROOT / 'Resources/Localizable.xcstrings'
    catalog = json.loads(path.read_text())
    for key, (en, zh) in PAIRS.items():
        catalog['strings'][key] = {'localizations': {lang: {'stringUnit': {'state': 'translated', 'value': text}} for lang, text in [('en', en), ('zh-Hans', zh)]}}
    path.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + '\n')
    print(f'Merged {len(PAIRS)} social/account strings')
