#!/usr/bin/env python3
"""Build an additive catalog fragment. Never overwrite the shared app catalog here."""
import json, pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
P={
"title":("Business workspace","经营工作区"),"workspace":("Business tools","经营工具"),
"customers":("Customers","客户名册"),"customer":("Customer details","客户详情"),"aftercare":("Aftercare","退款售后"),"refund":("Aftercare case","售后详情"),"reviews":("Reviews","评价管理"),"overview":("Finance overview","结算概览"),"redemptions":("Redemption ledger","核销台账"),"entries":("Income and adjustments","收入与调整"),"batches":("Public transfer batches","对公结算批次"),"batch":("Batch details","批次详情"),"redemption":("Redemption details","核销详情"),"verifications":("Verification actions","核销动作记录"),"operators":("Operator team","经营团队"),"roles":("Assignable roles","可分配岗位"),"scan":("Code route preview","核销码路由预览"),
"boundary":("Read current records and review actions. Availability depends on scoped approval and current permissions.","读取当前记录并预览操作。是否可提交取决于限定授权和当前权限。"),
"confirmProduction":("Confirm action","确认操作"),
"productionSaved":("Server response received","已收到服务端回执"),
"synthetic":("Offline example. All people, records and outcomes are synthetic.","离线示例。人物、记录与结果均为虚构测试数据。"),
"invalid":("Check the fields and try again.","请检查填写内容后重试。"),"malformed":("The response is incomplete or belongs to another record.","回执不完整，或与当前记录不一致。"),"denied":("Your current business identity does not have access.","当前经营身份没有此权限。"),"disabled":("Live dispatch is disabled. This review does not change any business record.","真实提交暂未启用。本次预览不会更改业务记录。"),"stale":("The account or session changed. Reload before continuing.","账号或会话已变化，请重新加载后继续。"),"conflict":("The record or permissions changed. Reload and review again.","记录或权限已变化，请刷新后重新预览。"),"unknownResult":("A previous request has an unknown result. Sending again is locked, including after reopening. A list refresh cannot prove its outcome.","之前请求的结果尚不确定。再次提交已锁定，重新打开也不会解除。刷新列表不能证明该请求的结果。"),"journal":("Recovery data could not be verified. Dispatch is blocked.","无法核验恢复记录，已阻止提交。"),"rejected":("The server rejected this request.","服务端拒绝了此请求。"),"loadFailed":("Could not load these records. Try again.","暂时无法加载记录，请重试。"),
"empty":("No records in this view.","当前视图暂无记录。"),"refresh":("Refresh records","刷新记录"),"filters":("Customer filters","客户筛选"),"search":("Search customers","搜索客户"),"segment":("Customer segment","客户分群"),"applyFilter":("Apply filters","应用筛选"),"bucket":("Aftercare status","售后分组"),"filter":("Settlement status","结算状态"),"previous":("Previous","上一页"),"next":("Next","下一页"),"page":("Page","页码"),"summary":("Server summary","服务端汇总"),
"segment.all":("All","全部"),"segment.repeat":("Returning","回头客"),"segment.new":("New","新客"),"segment.noted":("With notes","有备注"),"bucket.PENDING":("Awaiting response","待回应"),"bucket.PROCESSING":("Processing","处理中"),"bucket.COMPLETED":("Completed","已完成"),"filter.all":("All","全部"),"filter.pending":("Pending settlement","待结算"),"filter.settled":("Settled","已结算"),
"addNote":("Add follow-up note","添加跟进备注"),"hideNote":("Hide note","隐藏备注"),"correctNote":("Append correction","追加更正"),"assignTag":("Assign tag","添加标签"),"removeTag":("Remove tag","移除标签"),"batchTag":("Tag selected customers","批量添加标签"),"respond":("Prepare response","准备售后意见"),"review.reply":("Reply to review","回复评价"),"review.update":("Edit reply","修改回复"),"review.delete":("Delete reply","删除回复"),"review.report":("Report review","举报评价"),"inviteOperator":("Prepare operator invitation","准备团队邀请"),"changeRole":("Change role","修改岗位"),"removeOperator":("Remove operator","移除成员"),"revokeInvite":("Revoke invitation","撤销邀请"),
"receipt":("Response received","已收到回执"),"syntheticSaved":("Synthetic response received","已收到模拟回执"),"platformRefunded":("The platform response confirms a refund.","平台回执确认已退款。"),"opinionOnly":("A merchant opinion does not execute a refund. The platform determines the outcome.","商家意见不会执行退款。最终结果由平台确认。"),
"selectCustomer":("Select customer","选择客户"),"selected":("Selected","已选择"),"unselected":("Not selected","未选择"),"localActions":("Local draft actions","本地草稿操作"),"yes":("Yes","是"),"no":("No","否"),"notProvided":("Not provided","未提供"),"noCash":("No cash settlement","不产生现金结算"),"amountPending":("Amount not established","金额尚未成立"),"sensitiveUnavailable":("The server has not supplied an authorized spending amount.","服务端未提供可查看的消费金额。"),"imagesAvailable":("Review images","评价图片"),
"scanBoundary":("Preview a code's source route without opening a camera or redeeming it.","仅预览码的源路由，不打开摄像头，也不执行核销。"),"scanInput":("Paste code for local preview","输入核销码以本地预览"),"previewRoute":("Preview route","预览路由"),"preview":("Local preview","本地预览"),"unsupportedCode":("This dynamic code type is not supported.","暂不支持此动态码类型。"),"unverifiedCode":("Classification is not verification. Authenticity and eligibility require the server.","识别码型不等于验证。真实性与可核销资格须由服务端确认。"),"scanKind.group":("Group code","团码"),"scanKind.dynamicTicket":("Dynamic ticket","动态票码"),"scanKind.coupon":("Coupon code","优惠券码"),"scanKind.legacyTicket":("Legacy ticket with choice support","支持选章或选站的旧版票码"),
"localDraft":("This form is local until a frozen review is explicitly confirmed.","表单先保存在本页，预览确认前不会提交。"),"noteContent":("Follow-up note (up to 500 UTF-16 units)","跟进备注（最多500个UTF-16单元）"),"tagName":("Tag name","标签名称"),"tagColor":("Tag color, for example #2E6D5A","标签颜色，例如 #2E6D5A"),"decision":("Merchant opinion","商家意见"),"responseContent":("Opinion or reason","意见或原因"),"evidenceKey":("Existing evidence upload key","已有凭证上传对象键"),"evidenceHint":("Only the source evidence object-key format is accepted. Native image upload is not enabled.","仅接受源协议规定的凭证对象键格式。原生图片上传尚未启用。"),"deleteReplyWarning":("Prepare deletion of the existing public merchant reply.","准备删除现有公开商家回复。"),"reportReason":("Reason for reporting","举报原因"),"replyContent":("Public merchant reply","公开商家回复"),"role":("Role","岗位"),"chooseRole":("Choose a supplied role","选择服务端提供的岗位"),"permissions":("Permissions for this role","此岗位权限"),"rolesBoundary":("Role changes stay disabled in production. The server's current role list is authoritative.","生产岗位变更保持关闭，以服务端当前岗位列表为准。"),"reason":("Reason","原因"),"reviewDraft":("Review draft","预览草稿"),"frozenReview":("Frozen confirmation","冻结确认内容"),"storeID":("Store ID","门店ID"),"target":("Exact target","操作目标"),"refreshBeforeSend":("Before synthetic dispatch, access, store identity, target and version are fetched and checked again.","模拟提交前会重新读取并核对权限、门店身份、目标和版本。"),"confirmSynthetic":("Confirm in offline example","确认模拟提交"),"fixtureSignOut":("Sign out of example","退出示例账号")}
P.update({"sourceType":("Source type","来源类型"),"tag":("Store tag","店内标签"),"sourceStart":("Source start date (YYYY-MM-DD)","来源开始日期（YYYY-MM-DD）"),"sourceEnd":("Source end date (YYYY-MM-DD)","来源结束日期（YYYY-MM-DD）"),"systemTags":("System tags","系统标签"),"reviewImage":("Customer review image","客户评价图片"),"imageUnavailable":("Image unavailable","图片暂不可用")})
P.update({
"aftercare.search":("Search this page","搜索当前页"),
"aftercare.searchScope":("Search refund number, customer, activity or reason on this loaded page only. The same search is applied when you change pages or status.","仅搜索当前已加载页的退款单号、客户、活动或原因。切换页码或分组时保留搜索词并重新筛选。"),
"aftercare.clearSearch":("Clear search","清空搜索"),
"reviews.filter":("Review filter","评价筛选"),
"reviews.filter.all":("All reviews","全部评价"),
"reviews.filter.pending":("Awaiting reply","待回复"),
"reviews.filter.low":("3 stars or fewer","3星及以下"),
"reviews.filter.photos":("With photos","有图评价"),
"reviews.filterScope":("Filter the current loaded page only. The same filter is applied when you change pages.","仅筛选当前已加载页。切换页码时保留筛选条件并重新筛选。"),
"reviews.clearFilter":("Show all on this page","显示当前页全部评价"),
"reviews.summaryScope":("Server-provided review metrics. Filtering this page does not change these values.","以下为服务端评价统计，不随当前页筛选条件变化。"),
"list.noMatches":("No matching records on this page. Clear the filter or check another page.","当前页没有匹配记录。请清空筛选条件或查看其他页。"),
"field.customerNickname":("Customer nickname","客户昵称"),
"field.activityTitle":("Activity","活动名称"),
"field.pendingReplyCount":("Awaiting reply (server)","待回复（服务端）"),
"field.monthNewCount":("New reviews this month (server)","本月新增评价（服务端）"),
"field.replyRatePct":("Reply rate (server)","回复率（服务端）")
})
sections={"customers":("Customers","客户"),"customer":("Customer summary","客户摘要"),"tags":("Store tags","店内标签"),"timeline":("Customer timeline","客户时间线"),"aftercare":("Aftercare cases","售后申请"),"refund":("Refund request","退款申请"),"responses":("Merchant responses","商家回应记录"),"reviews":("Customer reviews","客户评价"),"redemption":("Redemption records","核销记录"),"entry":("Income and adjustments","收入与调整"),"batch":("Batch summary","批次摘要"),"earnings":("Earning entries","收入分录"),"adjustments":("Adjustment entries","调整分录"),"verifications":("Verification actions","核销动作"),"operators":("Team members","团队成员"),"invites":("Team invitations","团队邀请"),"roles":("Roles","岗位")}
P.update({"section."+k:v for k,v in sections.items()})
fields={
"personalArrivedThisMonthGross":("Personal channel gross this month","本月个人渠道到账毛额"),"personalExecutedAdjustmentsThisMonth":("Executed adjustments this month","本月已执行调整"),"personalArrivedThisMonthNet":("Personal channel net this month","本月个人渠道到账净额"),"publicPayablePending":("Public-channel amount pending","对公待打款"),"adjustmentPending":("Pending adjustments","待执行调整"),"adjustmentPendingCount":("Pending adjustment count","待执行调整笔数"),"count":("Count","笔数"),"pendingAmount":("Pending amount","待结算金额"),"arrivedAmount":("Arrived amount","已到账金额"),"averageRating":("Average rating","平均评分"),"all":("All customers","全部客户"),"repeat":("Returning customers","回头客"),"new":("New customers","新客"),"noted":("Customers with notes","有备注客户"),"monthlyNew":("New this month","本月新客"),
"phone":("Masked phone","脱敏号码"),"contactHint":("Contact status","联系状态"),"arrivedCount":("Visits","到店次数"),"pendingCount":("Pending","待核销次数"),"refundedCount":("Refunds","退款次数"),"paidAmount":("Authorized spending amount","可查看消费金额"),"lastInteractionTime":("Last interaction","最近互动时间"),"lastTime":("Last activity","最近活动时间"),"latestNote":("Latest note","最新备注"),"teamName":("Team","队伍"),"roleName":("Customer role","客户身份"),"tier":("Customer tier","客户分层"),"lastAction":("Last action","最近行为"),"sourceType":("Source type","来源类型"),"sourceId":("Source ID","来源ID"),"refundAmount":("Requested refund amount","申请退款金额"),"reason":("Reason","原因"),"processing":("Platform processing","平台处理状态"),"merchantOpinion":("Merchant opinion","商家意见"),"refundPolicyCode":("Policy snapshot code","退款政策快照代码"),"refundPolicyVersion":("Policy version","政策版本"),"refundDeadline":("Source deadline","源截止时间"),"createTime":("Created","创建时间"),"rating":("Rating","评分"),"content":("Content","内容"),"verifiedRedemption":("Verified redemption","已验证核销"),"status":("Status","状态"),"merchantReply":("Merchant reply","商家回复"),"repliedAt":("Replied","回复时间"),"version":("Version","版本"),"topicName":("Route","路线"),"chapterName":("Chapter","章节"),"storeName":("Store","门店"),"customerDisplayName":("Customer display name","客户展示名"),"verificationCodeTail":("Code tail","核销码尾号"),"fulfillmentState":("Fulfillment state","履约状态"),"settlementState":("Settlement state","结算状态"),"settlementRoute":("Settlement channel","结算渠道"),"displayState":("Source display state","源展示状态"),"settlementAmount":("Settlement amount","结算金额"),"noCashReason":("No-cash reason","不结现金原因"),"refundState":("Refund state","退款状态"),"occurredAt":("Occurred","发生时间"),"unitFee":("Source unit fee","源单价"),"headCount":("Head count","人数"),"entryKind":("Entry kind","分录类型"),"source":("Source","来源"),"destination":("Destination","去向"),"signedAmount":("Signed amount","带符号金额"),"arrivalAt":("Arrival time","到账时间"),"periodYm":("Period","账期"),"amountTotal":("Batch amount","批次金额"),"netDirection":("Net direction","净额方向"),"paymentState":("Payment state","打款状态"),"invoiceState":("Invoice state","发票状态"),"holdState":("Hold state","暂停状态"),"paidAt":("Paid at","打款时间"),"payVoucherNo":("Payment voucher","打款凭证号"),"roleCode":("Role","岗位"),"acceptedAt":("Joined","加入时间"),"expiresAt":("Expires","失效时间"),"name":("Name","名称"),"type":("Timeline type","时间线类型"),"description":("Description","描述"),"noteVersion":("Note version","备注版本"),"correctsNoteId":("Corrected note ID","被更正备注ID"),"tagName":("Tag name","标签名"),"tagColor":("Tag color","标签颜色"),"decision":("Decision","意见"),"actorRoleCode":("Acting role","操作岗位"),"operatorName":("Operator","核销成员"),"noteId":("Note ID","备注ID"),"expectedVersion":("Expected version","预期版本"),"tagId":("Tag ID","标签ID"),"customerMemberIds":("Selected customer IDs","所选客户ID"),"evidenceKeys":("Evidence object keys","凭证对象键"),"reviewId":("Review ID","评价ID"),"operatorId":("Operator ID","经营成员ID"),"inviteId":("Invitation ID","邀请ID")}
P.update({"field."+k:v for k,v in fields.items()})
states={
"WAITING_PLATFORM_REVIEW":("Platform review pending","平台审核中"),"PLATFORM_REJECTED":("Platform rejected refund","平台未通过退款"),"REFUND_PROCESSING":("Refund processing","退款处理中"),"MANUAL_REFUND_PENDING":("Manual refund pending","等待人工退款"),"MANUAL_REFUND_REVIEW":("Manual refund review pending","人工退款待复核"),"REFUNDED":("Refund confirmed by platform","平台确认已退款"),"UNKNOWN":("Not confirmed","待确认"),"PENDING":("Pending","待处理"),"AGREE":("Agree with request","同意申请"),"REJECT":("Recommend rejection","建议驳回"),"EVIDENCE":("Additional evidence","补充凭证"),"VISIBLE":("Publicly visible","公开展示中"),"PENDING_REVIEW":("Pending platform review","待平台复核"),"HIDDEN":("Hidden by platform","平台已下架"),"ACTIVE":("Active","生效中"),"REVOKED":("Revoked","已撤销"),"ACCEPTED":("Accepted","已接受"),"EXPIRED":("Expired","已过期"),"MERCHANT_OWNER":("Owner","店主"),"MERCHANT_MANAGER":("Manager","店长"),"MERCHANT_CHECKIN":("Check-in operator","核销员"),"MERCHANT_MARKETING":("Marketing","运营"),"MERCHANT_FINANCE":("Finance","财务"),"NO_CASH_SETTLEMENT":("No cash settlement","不结现金"),"PENDING_SETTLEMENT":("Pending settlement","待结算"),"SETTLED":("Settled","已结算"),"REVIEWING":("Under review","审核中"),"REJECTED":("Rejected","已驳回"),"REFUNDING":("Refund in progress","退款中"),"PAID":("Paid","已打款"),"PLATFORM_PAYS_MERCHANT":("Platform pays merchant","平台应付商家"),"MERCHANT_PAYS_PLATFORM":("Merchant pays platform","商家应付平台"),"pending":("Pending verification","待核销"),"abnormal":("Exception","异常"),"dormant":("Dormant","沉睡"),"repeat":("Returning customer","复购"),"new":("New customer","新客"),"TOPIC":("Route","主题"),"ACTIVITY":("Activity","活动"),"MIXED":("Mixed sources","多种来源")}
P.update({"state."+k:v for k,v in states.items()})
P.update({"role."+k:v for k,v in states.items() if k.startswith("MERCHANT_")})
strings={"merchant.business."+k:{"localizations":{language:{"stringUnit":{"state":"translated","value":pair[i]}} for i,language in enumerate(["en","zh-Hans"])}} for k,pair in sorted(P.items())}
(ROOT/'Resources'/'MerchantBusinessLocalizations.fragment.json').write_text(json.dumps(strings,ensure_ascii=False,indent=2)+'\n')
print(f'{len(strings)} bilingual keys written to additive fragment')
