#!/usr/bin/env python3
"""Produce a bilingual fragment. Does not mutate the shared catalog."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
copy = {
'recruiting': ('Open recruiting routes','开放承接路线'),
'reviewCircle': ('Confirm instance supply review','确认实例供给已复核'),
'circleRules': ('The server rechecks current supply. Missing, duplicate or expired supply does not count as a completed review.', '服务端将重新核对当前供给；供给不足、重复或过期时不视为复核完成。'),
'supplyUnknown': ('Active-supply status was not returned','未返回供给生效状态'),

'actualSupply': ('Actual chapter supply', '章节实际供给'), 'manageSupply': ('Open cooperation supply', '打开合作供给'),
'supplyActive': ('An active offer is recorded', '已记录生效供给'), 'supplyInactive': ('No active offer is recorded', '未记录生效供给'),
'supplyTermsUnknown': ('Terms are unavailable for this chapter; enrollment stays closed', '未取得本章承接档位，暂不能申报供给'),
'supplyLoadFailed': ('Supply context could not be loaded; other recruitment information remains available', '暂时无法读取供给上下文，其他招募信息仍可查看'),

'title': ('Projects & local content', '项目与据点内容'),
'entryHint': ('Review source records and prepare changes', '查看源记录并准备变更'),
'projects': ('Hosted projects', '我主办的项目'), 'chapters': ('Chapter recruitment', '章节招募'),
'applications': ('My chapter applications', '我的章节申请'), 'nodes': ('My chapter nodes', '我的章节点位'),
'upcoming': ('Upcoming visits', '即将到店的场次'), 'reviews': ('Application review', '承接申请审核'),
'invitable': ('Eligible invitees', '可邀请商家'), 'nodeReviews': ('Node review', '点位审核'),
'registrations': ('My registrations', '我的报名'), 'registration': ('Registration detail', '报名详情'),
'project': ('Project workspace', '项目工作台'), 'players': ('Player roster', '玩家名单'),
'city': ('City nodes', '城市据点'), 'claimable': ('Claimable places', '可认领地点'),
'placement': ('Place a city node', '申请投放据点'), 'npc': ('Chapter-node character', '章节点位角色'),
'voice': ('Node voice status', '节点声音状态'), 'games': ('Merchant game sessions', '商家互动场次'),
'game': ('Station workspace', '本站工作台'), 'poster': ('Poster check-in code', '海报打卡码'),
'liveCode': ('Live check-in code', '现场打卡码'), 'cityApplications': ('Placement and claim applications', '投放与认领申请'),
'quota': ('Active nodes / limit', '在架据点 / 上限'), 'edit': ('Edit registration', '修改报名'),
'apply': ('Apply for this chapter', '申请承接本章'), 'withdraw': ('Withdraw application', '撤回申请'),
'register': ('Register for this node', '报名承接本站'), 'cancelRegistration': ('Cancel registration', '取消报名'),
'invite': ('Pre-approve and invite', '预先批准并邀请'), 'auditApplication': ('Review application', '审核申请'),
'submitNode': ('Configure chapter node', '配置章节点位'), 'auditNode': ('Review node', '审核点位'),
'claim': ('Apply to claim', '申请认领'), 'cancelClaim': ('Withdraw claim', '撤回认领'),
'cityStatus': ('Change city-node availability', '变更据点上下架'), 'place': ('Submit placement application', '提交据点投放申请'),
'saveNPC': ('Edit node character', '编辑节点角色'), 'enrollVoice': ('Prepare node voice request', '准备节点录音申请'),
'resetVoice': ('Clear node voice', '清除节点声音'), 'online': ('Make available', '上架'), 'offline': ('Take offline', '下线'),
'filter': ('Registration status', '报名状态'), 'search': ('Search places', '搜索地点'),
'hosting': ('I am hosting', '我主办的'), 'joining': ('I am participating', '我承接的'),
'noWorkspace': ('No host or participant workspace was returned', '未返回主办或承接工作台'),
'empty': ('No records returned', '未返回记录'), 'noChapters': ('No open chapters were returned', '未返回开放招募的章节'),
'unlimitedSlots': ('No slot limit was supplied', '未设置名额限制'),
'alreadyRegistered': ('The server says you already registered', '服务端确认您已报名'),
'registrationUnknown': ('Registration status could not be confirmed', '暂时无法确认是否已报名'),
'npcUnconfigured': ('No character has been configured for this node', '此节点尚未配置角色'),
'firstPageOnly': ('More records exist beyond this source page', '源页面之外还有记录未加载'),
'disabled': ('Live actions are disabled. Edits and reviews remain local; test requests use an injected offline transport only.', '真实操作未启用。编辑和确认均保留在本地；测试请求仅使用注入的离线传输。'),
'voiceBoundary': ('Node voice uses one existing recording reference. Microphone, upload and provider generation are not enabled.', '节点声音使用一段已有录音引用。麦克风、上传和供应商生成均未启用。'),
'npcBoundary': ('This character belongs to this chapter node. Store-wide NPC settings are separate.', '此角色属于当前章节点位，与店铺级形象分开管理。'),
'mediaBoundary': ('Existing media references only. No image, audio or location is captured or uploaded.', '仅编辑已有媒体引用；不会采集或上传图片、录音或位置。'),
'supplyBoundary': ('Actual supply uses the separate cooperation workflow. An application ID is not an offer ID.', '实际供给由独立合作流程处理；申请编号不是供给编号。'),
'inviteWarning': ('An invitation is a pre-approved application, not just a message.', '邀请会建立预先批准的申请，并非仅发送消息。'),
'claimIDMissing': ('The source returned an application ID but no verified place ID. Claim withdrawal is unavailable.', '源数据仅返回申请编号，没有已核实的地点编号，暂不能撤回认领。'),
'applyTwoSteps': ('This step applies for the chapter. After the source refreshes, configure the node from My chapter applications. The two submissions are separate.', '此步骤提交章节申请。源数据更新后，请在“我的章节申请”配置点位。两次提交分别处理。'),
'nodeReviewWarning': ('Node changes are submitted for source review. Applying does not mean winning the slot.', '点位变更提交后由服务端处理审核；报名成功不等于中标。'),
'xpUnavailable': ('Exploration-value editing is unavailable: the retained source says the backend validates it without persisting it.', '探索值暂不可编辑：保留的源记录表明后端会校验，但不会保存。'),
'placementWarning': ('A successful placement submission creates a pending application. It does not put the node online.', '投放提交成功后形成待审申请，不代表据点已上线。'),
'confirmAddress': ('I have checked the address and coordinates', '我已核对店址与坐标'),
'registrationContent': ('Venue and registration content', '场地与报名内容'),
'registrationPreservation': ('Route, node, template, award and settlement fields are fixed. Source dates remain unchanged. Empty capacity submits zero, meaning unlimited.', '路线、站点、模板、中标和结算字段不可更改；保留原日期。人数留空将提交 0，表示不限。'),
'approve': ('Approve', '通过'), 'auditWarning': ('Approval controls admission; it is not a platform endorsement.', '通过仅代表准入，不代表平台背书。'),
'completeFields': ('Complete the source-required fields before review', '请完成源契约要求的字段后再预览'),
'review': ('Review frozen request', '预览冻结请求'), 'confirm': ('Run offline test request', '执行离线测试请求'),
'immutableReview': ('This review freezes the target and fields. Permissions and source data are checked again before dispatch.', '此预览已冻结目标与字段，发送前会重新核对权限和源数据。'),
'reviewWarning': ('A server acknowledgement is not publication, a completed review or a successful financial result. Unknown outcomes stay locked.', '服务端回执不代表发布、审核通过或资金操作成功；结果未知时保持锁定。'),
'discardTitle': ('Discard local edits?', '放弃本地修改？'), 'discard': ('Discard and leave', '放弃并退出'), 'keepEditing': ('Keep editing', '继续编辑'),
'reconcile': ('Check the original station receipt', '核对原本站操作回执'),
'retryOriginal': ('Retry the frozen station request', '重试原冻结的本站请求'),
'retryOriginalWarning': ('Check the receipt, then replay only the same station request if the server still permits it?', '先核对回执；仅当服务端仍允许时，重放同一本站请求？'),
'stationReviewWarning': ('This affects only the selected merchant station', '此操作仅影响所选商家站点'),
'civilTime': ('Enter the service civil time as YYYY-MM-DD HH:mm. The source provides no timezone; the server validates eligibility.', '请输入服务端本地时间 YYYY-MM-DD HH:mm。源数据未提供时区，时间资格由服务端校验。'),
'fallback': ('Server-provided fallback plan', '服务端提供的备援预案'), 'template': ('Owned interaction template', '我的互动模板'),
'chooseTemplate': ('Choose a template', '选择模板'), 'chooseReason': ('Choose a reason', '选择原因'),
'codeExpired': ('This live code expired. Reload to request a new code.', '此现场码已过期，请刷新获取新码。'),
'liveCodeWarning': ('Time-limited live code. It is hidden on expiry.', '现场码有有效期，到期后将隐藏。'),
'posterWarning': ('Poster code is separate from the time-limited live code', '海报码与限时现场码分开使用'),
'invalid': ('Check the requested fields and target', '请核对请求字段与目标'), 'malformed': ('Source data could not be safely read', '无法安全读取源数据'),
'denied': ('Current access does not permit this operation', '当前权限不允许此操作'),
'sessionChanged': ('The signed-in account or session changed. Reopen this screen.', '登录账号或会话已变更，请重新打开此页面。'),
'conflict': ('The source changed after review. Reload and review again.', '预览后源数据已发生变化，请重新加载并确认。'),
'storage': ('Recovery state could not be saved safely. Nothing was sent.', '无法安全保存恢复状态，因此未发送请求。'),
'unknown': ('The result is unknown. Do not repeat this action. Only an exact terminal station receipt can release a station lock.', '结果未知，请勿重复操作。本站锁仅可由完全匹配的终态回执解除。'),
'rejected': ('The server rejected this request', '服务端拒绝了此请求'), 'signedOut': ('Sign in again to continue', '请重新登录后继续'),
'loadFailed': ('Could not load the source. Retry when ready.', '暂时无法加载源数据，请稍后重试。'),
'acknowledged': ('The source acknowledged this request. Reload to inspect its current state.', '服务端已确认收到请求，请刷新核对当前状态。'),
'stationFailed': ('The station receipt confirms this operation failed', '本站回执确认操作失败'), 'reconciled': ('The original station receipt is terminal. Reload the current source state.', '原本站回执已到终态，请重新加载当前源状态。'),
'fixtureSignOut': ('Switch test account', '切换测试账号'), 'fixtureRecover': ('Restore test reads', '恢复测试读取'),
'fixtureBanner': ('Synthetic offline data. No business action is performed.', '离线合成数据，不执行真实业务操作。'),
}
fields = {
'merchantSignUpEndDate': ('Recruitment deadline','商家报名截止日期'),
'circleReviewedAt': ('Instance last reviewed','实例最近复核时间'),
'offerId': ('Offer ID','供给编号'),
'merchantName': ('Merchant name','商家名称'),
'addressName': ('Venue name','场地名称'), 'address': ('Address','地址'), 'longitude': ('Longitude','经度'), 'latitude': ('Latitude','纬度'),
'activityDesc': ('Hosting description','承接说明'), 'picUrl': ('Image references, comma separated','图片引用，以逗号分隔'), 'limitNum': ('Capacity, blank means unlimited','人数限制，留空表示不限'),
'cooperateDate': ('Available hours','可配合时间'), 'name': ('Name','名称'), 'description': ('Description','描述'), 'imgUrl': ('Image reference','图片引用'), 'businessTime': ('Business hours','营业时间'),
'avatar': ('Avatar reference','角色头像引用'), 'greeting': ('Greeting','招呼语'), 'voiceSample': ('Recording reference','录音引用'), 'voiceStatus': ('Voice state from source','源声音状态'),
'tags': ('Tags','标签'), 'coverImg': ('Cover reference','封面引用'), 'cityCode': ('City code','城市代码'), 'message': ('Application message','申请说明'),
'reason': ('Reason','原因'), 'reasonCode': ('Reason category','原因类别'), 'capacity': ('Capacity','接待人数'), 'serviceStartAt': ('Service starts','服务开始时间'), 'serviceEndAt': ('Service ends','服务结束时间'), 'note': ('Preparation note','准备备注'),
'resumeEta': ('Expected resumption','预计恢复时间'), 'submissionId': ('Submission ID','玩家提交编号'), 'merchantID': ('Merchant ID','门店编号'),
'nodeName': ('Node name','节点名称'), 'topicName': ('Route name','路线名称'), 'chapterName': ('Chapter name','章节名称'), 'status': ('Source status','源状态'), 'auditStatus': ('Source review status','源审核状态'),
'startDate': ('Source start date','源开始日期'), 'endDate': ('Source end date','源结束日期'), 'paidCount': ('Paid players','已付款人数'), 'arrivedCount': ('Arrived players','已到人数'),
'pendingCount': ('Pending count','待处理数量'), 'refundedCount': ('Refunded players','已退款人数'), 'templateTitle': ('Template title','模板名称'), 'auditReason': ('Review reason','审核原因'),
'rejectReason': ('Rejection reason','驳回原因'), 'applicationType': ('Application type','申请类型'), 'startTime': ('Start time','开始时间'), 'clubName': ('Club','俱乐部'), 'teamStatus': ('Team state','成团状态'),
'arrivalStart': ('Estimated arrival from','预计到店起始'), 'arrivalEnd': ('Estimated arrival until','预计到店截止'), 'source': ('Application source','申请来源'), 'auditRemark': ('Review remarks','审核备注'),
'circleSupplyCheckedAt': ('Supply last confirmed','供给最近确认时间'), 'nodeAuditStatus': ('Node review state','节点审核状态'), 'nodeAuditReason': ('Node review reason','节点审核原因'), 'stateText': ('State','状态'),
'startAt': ('Starts','开始'), 'endAt': ('Ends','结束'), 'stationCount': ('Station count','站点数量'), 'ticketName': ('Ticket','票种'), 'state': ('Source state','源状态'), 'phone': ('Phone supplied by server','服务端提供的电话'),
'category': ('Recruiting category','招募品类'), 'required': ('Required chapter flag','必选章节标记'), 'termsMode': ('Terms mode','承接档位'), 'perkMinValue': ('Minimum retail value (source amount)','最低零售价（源金额）'),
'allowedValidationMethods': ('Allowed validation methods','允许的核验方式'), 'maxNodeXp': ('Published XP limit','公示探索值上限'), 'maxMerchant': ('Merchant limit','商家名额上限'), 'remainingMerchantCount': ('Remaining slots','剩余名额'),
'city': ('City','城市'), 'title': ('Title','标题'), 'nodeFilled': ('Filled nodes','已承接节点'), 'nodeTotal': ('Total nodes','总节点数'), 'revision': ('Revision','版本'), 'stationCode': ('Station code','站点代码'),
'merchantInstruction': ('Merchant instruction','商家执行说明'), 'hiddenInfoReminder': ('Private-information reminder','隐藏信息提醒'), 'pendingVerificationCount': ('Pending submissions','待核验提交'),
'arrivedPlayers': ('Arrived players','到场玩家'), 'submissionCount': ('Submissions','提交数量'), 'approvedCount': ('Approved','通过数量'), 'rejectedCount': ('Rejected','拒绝数量'), 'recordedCount': ('Recorded','已记录数量'),
'normalCompletedCount': ('Normal completions','正常完成数量'), 'fallbackCompletedCount': ('Fallback completions','备援完成数量'), 'pauseEventCount': ('Pauses','暂停次数'), 'code': ('Check-in code','打卡码'),
}
copy.update({'field.'+k:v for k,v in fields.items()})
for i, pair in enumerate([('All','全部'),('Ongoing','进行中'),('Under review','审核中'),('Rejected','已驳回'),('Ended','已结束')]): copy['filter.'+str(i)] = pair
copy.update({
'STATION_ACCEPT': ('Accept station invitation','接受本站邀请'), 'STATION_DECLINE': ('Decline station invitation','拒绝本站邀请'),
'STATION_READY': ('Prepare station','准备本站'), 'STATION_PAUSE': ('Pause station','暂停本站'), 'STATION_RESUME': ('Resume station','恢复本站'), 'VERIFY_SUBMISSION': ('Review player submission','核验玩家提交'),
})
for k,v in {
'SCHEDULE_CONFLICT':('Schedule conflict','档期冲突'), 'RESOURCE_UNAVAILABLE':('Resources unavailable','现场资源不足'), 'LOCATION_UNSUITABLE':('Location unsuitable','本站不适合承接'),
'CAPACITY':('At capacity','现场满员'), 'STAFF':('Staff unavailable','人员暂时离岗'), 'EQUIPMENT':('Equipment problem','设备或道具异常'), 'EMERGENCY':('Emergency','现场突发情况'),
'ANSWER_MISMATCH':('Answer mismatch','答案不符'), 'EVIDENCE_UNCLEAR':('Evidence unclear','证据不清'), 'DUPLICATE_SUBMISSION':('Duplicate submission','重复提交'),
}.items(): copy['reason.'+k] = v
fragment = {'merchant.content.'+k:{'localizations':{lang:{'stringUnit':{'state':'translated','value':value}} for lang,value in zip(['en','zh-Hans'],pair)}} for k,pair in sorted(copy.items())}
(ROOT/'Resources/MerchantContentLocalizations.fragment.json').write_text(json.dumps(fragment,ensure_ascii=False,indent=2)+'\n')
print(f'Authored {len(fragment)} bilingual keys; no runtime validation')
