import json
from pathlib import Path
pairs = {
 'scope.agree':('I have read and agree to the displayed notice','我已阅读并同意所示须知'), 'scope.confirm':('Confirm consent','确认授权'),
 'title':('Account privacy','账号隐私'), 'roam':('Roam location consent','漫游定位授权'), 'marketing':('Marketing preferences','营销偏好'), 'cancellation':('Close account','注销账号'),
 'loading':('Loading…','加载中…'), 'close':('Close','关闭'), 'cancelReview':('Cancel this account-closure application?','撤销此次账号注销申请？'), 'cancelApplication':('Cancel application','撤销申请'), 'serverStatus':('Server status','服务端状态'), 'executeAfter':('Scheduled execution','预计执行时间'), 'agreeNotice':('I have read and agree to the cancellation notice','我已阅读并同意账号注销须知'), 'precheck':('Check eligibility and agree','检查资格并同意'), 'legalMissing':('Approved regional legal content is unavailable. This action cannot be enabled.','已批准的地区法律文档尚不可用，暂不能启用此操作。'), 'phone':('Bound phone number','已绑定手机号'), 'sendSMS':('Send verification code','发送验证码'), 'smsSent':('Verification code sent','验证码已发送'), 'code':('Verification code','验证码'), 'review':('Review application','确认申请内容'), 'reviewWarning':('Submitting may revoke all sessions. Sign in again to check or cancel a pending application. The server determines eligibility and the execution date.','提交后可能吊销所有会话。请重新登录查询或撤销在途申请。注销资格和执行时间以服务端为准。'), 'submit':('Submit account closure','提交注销申请'), 'back':('Go back','返回'), 'pending':('An application is pending. The date and blockers above come from the server.','申请正在处理中。以上日期及阻断项由服务端提供。'), 'freshLogin':('Application accepted. Sign in again before checking or cancelling it.','申请已受理，请重新登录后查询或撤销。'), 'unknown':('The outcome is unconfirmed. Do not submit again. Refresh status or contact support.','结果尚未确认，请勿重复提交。请刷新状态或联系支持。'), 'refresh':('Refresh status','刷新状态'), 'readPrivacy':('Read privacy policy','阅读隐私政策'), 'roamExplanation':('Revoke server consent, then stop tracking and clear local map privacy agreement. A failed local step can be resumed.','先撤回服务端授权，再停止定位并清除本地地图隐私同意。失败的本地步骤可以继续。'), 'revoke':('Revoke or finish local cleanup','撤回授权或继续本地清理'), 'marketingExplanation':('Preferences change only after the server confirms this merchant and channel.','仅在服务端确认对应商家及渠道后更新偏好。'), 'merchant':('Merchant','商家'), 'channel.IN_APP':('In-app marketing','应用内营销'), 'channel.COUPON':('Coupon marketing','优惠券营销'), 'unavailable':('This action is not enabled for this environment.','当前环境未启用此操作。'), 'failed':('The operation did not complete. Check the current state before trying again.','操作未完成，请先检查当前状态再重试。'), 'codeRequired':('Enter a valid verification code','请输入有效验证码'), 'cleanup.idle':('Consent has not been revoked','授权尚未撤回'), 'cleanup.serverConfirmed':('Consent revoked; tracking cleanup remains','授权已撤回，仍需停止定位'), 'cleanup.trackingStopped':('Tracking stopped; local privacy cleanup remains','定位已停止，仍需清理本地隐私状态'), 'cleanup.complete':('Consent revoked and local cleanup completed','授权已撤回，本地清理已完成')
}
root=Path(__file__).resolve().parents[1]
(root/'Resources/AccountCompliance.xcstrings').write_text(json.dumps({'sourceLanguage':'en','strings':{'compliance.'+k:{'localizations':{lang:{'stringUnit':{'state':'translated','value':value}} for lang,value in zip(('en','zh-Hans'),v)}} for k,v in pairs.items()},'version':'1.0'},ensure_ascii=False,indent=2)+'\n')
