#!/usr/bin/env python3
"""Static/source evidence only. Authored Swift tests are not executed by this script."""
from pathlib import Path
import argparse, hashlib, json, re, subprocess
p=argparse.ArgumentParser();p.add_argument('--flutter-root',type=Path);p.add_argument('--syntax-python',type=Path);p.add_argument('--syntax-script',type=Path);args=p.parse_args()
root=Path(__file__).resolve().parents[1]
flutter=args.flutter_root or root.parent/'app-audit'
api=(flutter/'lib/data/api/merchant_api.dart').read_text(); predict=(flutter/'lib/data/api/merchant_predict_api.dart').read_text(); insight_source=(flutter/'lib/data/models/merchant_insight.dart').read_text(); subscription_source=(flutter/'lib/feature/merchant/merchant_subscription_page.dart').read_text()
models=(root/'Core/MerchantMarketingModels.swift').read_text(); service=(root/'Core/MerchantMarketingService.swift').read_text(); coordinator=(root/'Core/MerchantMarketingCoordinator.swift').read_text(); ui=(root/'App/MerchantMarketingView.swift').read_text(); fixture=(root/'Core/MerchantMarketingFixtures.swift').read_text()
checks=[]
def check(name, condition):
    if not condition: raise AssertionError(name)
    checks.append(name)
paths=set(re.findall(r'"(api/[^"\n]+)"',service))
expected={'api/merchant/access/me','api/merchant/marketing-home','api/ai/merchant/insight','api/merchant/subscription','api/merchant/commerce/capabilities','api/merchant/predict/inbox','api/merchant/predict/settle'}
check('Exact source-backed endpoint set',paths==expected)
for path in paths:check('Source endpoint '+path,'/'+path in api+predict)
check('POST only', 'request.httpMethod = "POST"' in service and '"GET"' not in service)
check('Concrete injected HTTP dispatch', 'transport: any HTTPTransport' in service and 'await transport.send(request)' in service)
check('Reads default off', 'reads: Bool = false' in service)
check('AI default off and separate', 'insight: Bool = false' in service and 'guard permitsInsight' in service)
check('Settlement default off and separate', 'settlement: Bool = false' in service and 'guard permitsSettlement' in service)
check('No automatic live factory', 'Gates = Gates()' in service)
check('Marketing permission', 'permissions.contains("merchant:marketing:read")' in models)
check('Prediction permission', 'permissions.contains("merchant:project:manage")' in models)
check('Permission-before-dashboard', service.index('guard access.canReadMarketing')<service.index('request("api/merchant/marketing-home"'))
check('Permission-before-inbox', 'guard access.canSettlePrediction' in service)
check('Active authority', 'active && permissions.contains' in models)
check('Fixed roles validated', all(role in models for role in ['MERCHANT_OWNER','MERCHANT_MANAGER','MERCHANT_CHECKIN','MERCHANT_MARKETING','MERCHANT_FINANCE']))
check('No redundant coupon/funnel calls', not re.search(r'api/(coupon|merchant/funnel)',service))
check('No-body marketing and insight', all(f'request("{path}", session:' in service for path in ['api/merchant/marketing-home','api/ai/merchant/insight']))
for path in ['api/merchant/subscription','api/merchant/commerce/capabilities','api/merchant/predict/inbox']:check('Empty JSON body '+path,f'request("{path}", body: [:], session:' in service)
check('Insight facts mandatory', 'guard raw["facts"].object != nil' in models)
check('Insight retains metadata', 'metadata = raw' in models and 'aiError = raw["aiError"].text' in models)
for route in ['topic_coop','decor','content']:check('Allowlisted suggestion '+route,route in models and "'"+route+"'" in insight_source)
check('Typed navigation only', 'onSuggestion: (MerchantInsightDestination)' in ui and 'openURL' not in ui)
check('Unknown metric nullable', 'couponCount: Int?' in models and 'received > 0' in models)
check('Empty active entitlement state', 'if subscriptions.isEmpty' in ui)
check('Null end date permanent', 'isPermanent: Bool { endDate == nil }' in models and 'endDate == null' in subscription_source)
check('iOS checkout suppressed', 'iOSCheckoutAvailable: Bool { false }' in models and 'defaultTargetPlatform != TargetPlatform.iOS' in subscription_source)
check('No purchase implementation', '/commerce/order' not in service and 'StoreKit' not in service+ui)
check('Inbox array required', 'guard let rows = raw.array' in service)
for field in ['nodeId','playDay','settledOption']:check('Settlement field '+field,'"'+field+'": .string(' in service and "'"+field+"'" in predict)
check('Winners not invented', 'guard let winners = data["winners"].integer, winners >= 0' in service)
check('Review immutable and issued', 'public let id: UUID, scope:' in models and 'issued == review' in service)
check('Coupon consequences acknowledged', 'acknowledgedCouponEffects' in service and 'merchantMarketing.couponWarning' in ui)
check('Fresh access at review and commit', 'freshAccess == review.access' in service)
check('Fresh exact round', 'current.contains(review.round)' in service)
check('Journal before dispatch', service.index('try locks.acquire(record)')<service.index('request("api/merchant/predict/settle"'))
check('Exclusive durable lock creation', '.withoutOverwriting' in service)
check('Lock namespace/account/merchant/day', '[namespace, String(accountID), String(merchantID), nodeID, playDay]' in service)
lock=service[:service.index('@MainActor public protocol')]
check('Lock excludes token and epoch','token' not in lock and 'epoch' not in lock)
check('Unknown remains locked', 'throw MerchantMarketingFailure.unknown' in service and 'Keep a terminal replay lock' in service)
check('No invented receipt or retries', 'receipt' not in '\n'.join(re.findall(r'"api/[^"\n]+"',service)) and 'retry' not in '\n'.join(re.findall(r'"api/[^"\n]+"',service)))
check('Session checked around HTTP', service.count('try ensure(session)')>=2)
check('Coordinator discards stale results', 'generation == ticket' in coordinator and 'service.scope == scope' in coordinator)
check('Account change clears views', 'dashboard = nil; insight = nil; subscriptions = nil' in coordinator)
check('Review dismissed safely', '.interactiveDismissDisabled(model.busy)' in ui)
check('Feature visibility default off', 'isSourceVisible = false' in ui)
check('Fixture release excluded', fixture.startswith('#if DEBUG'))
check('Fixture never networks', 'URLSession' not in fixture and 'send(_ request:' in fixture)
fragment=json.loads((root/'Resources/MerchantMarketingLocalizations.fragment.json').read_text())
for path in [*root.glob('Core/*.swift'),*root.glob('App/*.swift')]:
    text=re.sub(r'\.accessibilityIdentifier\([^\n]*','',path.read_text())
    for key in set(re.findall(r'"(merchantMarketing\.[A-Za-z]+)"',text)): check('Localized '+key,key in fragment)
for key,value in fragment.items():check('Bilingual '+key,{'en','zh-Hans'}<=set(value['localizations']))
core_tests=len(re.findall(r'func test', (root/'Tests/CoreTests/MerchantMarketingTests.swift').read_text()))
ui_tests=len(re.findall(r'func test', (root/'Tests/AppUITests/MerchantMarketingUITests.swift').read_text()))
result={'static_source_checks':'PASS','check_count':len(checks),'swift_compilation':'NOT_RUN','swift_unit_tests':'NOT_RUN','ios_ui_runtime':'NOT_RUN','authored_core_test_cases':core_tests,'authored_ui_test_cases':ui_tests,'localization_keys':len(fragment),'real_network_requests':0,'live_grants':False,'digital_checkout':'NOT_IMPLEMENTED_SOURCE_IOS_SUPPRESSION','parser':'NOT_RUN'}
if args.syntax_python:
    syntax=args.syntax_script or root.parent/'chengyin-ios/tools/check_swift_syntax.py'
    swift=sorted(str(path.relative_to(root)) for directory in ['App', 'Core', 'Tests/CoreTests', 'Tests/AppUITests'] for path in (root/directory).glob('MerchantMarketing*.swift'))
    run=subprocess.run([str(args.syntax_python.absolute()),str(syntax.resolve()),'--root',str(root),*swift],capture_output=True,text=True)
    (root/'docs/merchant-marketing/parser.txt').write_text(run.stdout+run.stderr)
    if run.returncode:raise RuntimeError(run.stdout+run.stderr)
    result['parser']='PASS_SUPPLEMENTARY_ONLY';result['parsed_swift_files']=len(swift)
(root/'docs/merchant-marketing/validation.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps(result,indent=2))
